! -*- fortran -*-
! $HEADER$
!
! *** THIS FILE IS AUTOMATICALLY GENERATED!
! *** Any manual edits will be lost!
!
#include "ompi/mpi/fortran/configure-fortran-output.h"

module mpi_f08_ext
!     Some mpi_f08_ext extensions may require the mpi_f08 module.
      use mpi_f08
!
!     Even though this is not a useful parameter (cannot be used as a
!     preprocessor catch) define it to keep the linker from complaining
!     during the build.
      integer OMPI_HAVE_MPI_EXT
      parameter (OMPI_HAVE_MPI_EXT=1)
!
!
!     Enabled Extension: affinity
!     No "use mpi_f08" bindings available
!

!
!     Enabled Extension: cuda
!     No "use mpi_f08" bindings available
!

!
!     Enabled Extension: ftmpi
!
#include "./ompi/mpiext/ftmpi/mpif-h/mpiext_ftmpi_mpifh.h"
#include "./ompi/mpiext/ftmpi/use-mpi-f08/mpiext_ftmpi_usempif08.h"

!
!     Enabled Extension: rocm
!     No "use mpi_f08" bindings available
!

!
end module mpi_f08_ext
